CREATE TABLE CONFIGURACJA 
   (CONF_ID VARCHAR(20) NOT NULL, 
	DATA_POCZ DATE NOT NULL, 
	DATA_KONC DATE, 
	PAR_CHAR VARCHAR(20), 
	PAR_INT INTEGER, 
	KWOTA NUMERIC(25,2) DEFAULT 0, 
	KURS_ULAMKOWY NUMERIC(8,7), 
	KTO VARCHAR(20) NOT NULL, 
	KIEDY TIMESTAMP NOT NULL, 
	CONSTRAINT CONFIGURACJA_PK PRIMARY KEY (CONF_ID));