CREATE TABLE CONFIGURACJA 
   (CONFID VARCHAR(20) NOT NULL, 
	DATAPOCZ DATE NOT NULL, 
	DATAKONC DATE, 
	PARCHAR VARCHAR(20), 
	PARINT INTEGER, 
	KWOTA NUMERIC(25,2) DEFAULT 0, 
	KURSULAMKOWY NUMERIC(8,7), 
	KTO VARCHAR(20) NOT NULL, 
	KIEDY TIMESTAMP (0) NOT NULL, 
	 CONSTRAINT CONFIGURACJA_PK PRIMARY KEY (CONFID));
	 
   COMMENT ON COLUMN "CONFIGURACJA"."CONFID" IS 'Identyfikator';
 
   COMMENT ON COLUMN "CONFIGURACJA"."DATAPOCZ" IS 'Data początkowa';
 
   COMMENT ON COLUMN "CONFIGURACJA"."DATAKONC" IS 'Data końcowa - pusta bez ograniczeń';
 
   COMMENT ON COLUMN "CONFIGURACJA"."PARCHAR" IS 'Parametr znakowy';
 
   COMMENT ON COLUMN "CONFIGURACJA"."PARINT" IS 'Parametr liczby naturalnej';
 
   COMMENT ON COLUMN "CONFIGURACJA"."KWOTA" IS 'Kwota';
 
   COMMENT ON COLUMN "CONFIGURACJA"."KURSULAMKOWY" IS 'Liczba ułamkowa - np. kurs wal.';
 
   COMMENT ON COLUMN "CONFIGURACJA"."KTO" IS 'Kto wprowadził';
 
   COMMENT ON COLUMN "CONFIGURACJA"."KIEDY" IS 'Kiedy wprowadzono rekord';
 
   COMMENT ON TABLE "CONFIGURACJA"  IS 'Przykładowa tabelka konfiguracji';
 
create sequence CONFIGURACJA_SEQ;

CREATE OR REPLACE TRIGGER "CONFIGURACJA_TRG" BEFORE INSERT ON CONFIGURACJA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.CONFID IS NULL THEN
      SELECT CONFIGURACJA_SEQ.NEXTVAL INTO :NEW.CONFID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CONFIGURACJA_TRG" ENABLE
/

 