CREATE TABLE CONFIGURACJA 
   (CONFID VARCHAR(20) NOT NULL, 
	DATAPOCZ DATE NOT NULL, 
	DATAKONC DATE, 
	PARCHAR VARCHAR(20), 
	PARINT INTEGER, 
	KWOTA NUMERIC(25,2) DEFAULT 0, 
	KURSULAMKOWY NUMERIC(8,7), 
	KTO VARCHAR(20) NOT NULL, 
	KIEDY TIMESTAMP (0) NOT NULL, 
	 CONSTRAINT CONFIGURACJA_PK PRIMARY KEY (CONFID));
 
create sequence CONFIGURACJA_SEQ;

 